package org.duofold.live.wallpaperlayer;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.widget.*;import rikka.shizuku.Shizuku;import java.io.*;
public class WallpaperActivity extends Activity {
 TextView status; Handler h=new Handler(); IBinder remote; boolean connecting=false,startOnConnect=false; File photo; Shizuku.UserServiceArgs args;
 final ServiceConnection connection=new ServiceConnection(){public void onServiceConnected(ComponentName n,IBinder b){remote=b;connecting=false;if(startOnConnect){startOnConnect=false;startRemote();}else{h.removeCallbacks(poll);h.post(poll);}}public void onServiceDisconnected(ComponentName n){remote=null;status.setText("Shizuku connection ended. Reopen Shizuku if needed; Disable wallpaper still removes the photo layer.");}};
 final Shizuku.OnRequestPermissionResultListener permission=(a,b)->runOnUiThread(()->status.setText(b==0?"Authorized. Choose a photo and start.":"Shizuku permission denied."));
 public void onCreate(Bundle s){super.onCreate(s);photo=new File(getFilesDir(),"photo.jpg");if(!photo.exists()){File staged=new File(getFilesDir(),"chosen-home-background.jpg");if(staged.exists())try{java.nio.file.Files.copy(staged.toPath(),photo.toPath());}catch(Exception ignored){}}LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(30,50,30,30);root.setBackgroundColor(0xff151824);
 TextView title=new TextView(this);title.setText("Custom wallpaper");title.setTextSize(25);title.setTextColor(-1);root.addView(title);
 TextView info=new TextView(this);info.setText("Your photo below the home-screen icons, with Samsung’s hinge-aware wallpaper still running underneath. Keep Duo Fold Live enabled. There is no time limit: leave this screen and the photo stays active. Enable again after a reboot or if Android ends the host. Starting keeps the fold animation running. Choose another photo to change it while running. Disable restores the visible Samsung wallpaper.");info.setTextColor(0xffccd1e0);root.addView(info);
 status=new TextView(this);status.setTextColor(-1);status.setText("Choose a photo, authorize Shizuku, then start.");root.addView(status);
 CheckBox renderer=new CheckBox(this);renderer.setText("Native compositor photo · apply on next enable");renderer.setTextColor(-1);renderer.setChecked(!new File(getFilesDir(),"legacy-renderer").exists());renderer.setOnCheckedChangeListener((v,checked)->{try{File marker=new File(getFilesDir(),"legacy-renderer");if(checked)marker.delete();else marker.createNewFile();status.setText("Renderer saved. Disable, then enable the wallpaper to apply.");}catch(Exception e){status.setText(e.toString());}});root.addView(renderer);
 CheckBox wake=new CheckBox(this);wake.setText("Independent wake photo · apply on next enable");wake.setTextColor(-1);wake.setChecked(!new File(getFilesDir(),"disable-wake-layer").exists());wake.setOnCheckedChangeListener((v,checked)->{try{File marker=new File(getFilesDir(),"disable-wake-layer");if(checked)marker.delete();else marker.createNewFile();status.setText("Wake renderer saved. Disable, then enable wallpaper to apply.");}catch(Exception e){status.setText(e.toString());}});root.addView(wake);
 button(root,"Authorize Shizuku",()->{try{if(!Shizuku.pingBinder())status.setText("Start Shizuku first.");else if(Shizuku.checkSelfPermission()==0){status.setText("Shizuku authorized. Reconnecting report observer…");reconnectForReport();}else Shizuku.requestPermission(1);}catch(Exception e){status.setText(e.toString());}});
 button(root,"Choose / change photo",()->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),2));
 button(root,"Enable custom wallpaper",()->{try{if(!photo.exists()){status.setText("Choose a photo first.");return;}if(!Shizuku.pingBinder()||Shizuku.checkSelfPermission()!=0){status.setText("Authorize Shizuku first.");return;}if(remote!=null&&remote.isBinderAlive()){startRemote();return;}if(connecting)return;startOnConnect=true;connecting=true;args=new Shizuku.UserServiceArgs(new ComponentName(this,HostLauncher.class)).daemon(true).processNameSuffix("wallpaper_layer").version(16);Shizuku.bindUserService(args,connection);status.setText("Connecting…");}catch(Exception e){connecting=false;status.setText(e.toString());}});
 button(root,"Disable custom wallpaper",()->{try{new File(getFilesDir(),"stop-layer").createNewFile();status.setText("Stop requested; removing photo layer.");h.removeCallbacks(poll);h.postDelayed(poll,200);}catch(Exception e){status.setText(e.toString());}});
 TextView lockInfo=new TextView(this);lockInfo.setText("Optional lock-screen customization (did not fix the unlock flash): set your selected photo as BOTH lock-screen wallpapers. This is a persistent change, independent of the Enable toggle. Restore your previous lock wallpaper through Samsung settings. Samsung’s home wallpaper remains the hinge source.");lockInfo.setTextColor(0xffccd1e0);root.addView(lockInfo);
 button(root,"Apply this photo to both lock screens",()->{if(!photo.exists()){status.setText("Choose a photo first.");return;}h.removeCallbacks(poll);status.setText("Applying lock-screen photos…");new Thread(()->{String result;try{result=LockPhotoApplier.apply(this,photo);java.nio.file.Files.write(new File(getFilesDir(),"lock-photo-status.txt").toPath(),result.getBytes(java.nio.charset.StandardCharsets.UTF_8));}catch(Exception e){result="Lock photo action failed: "+e;}final String message=result;runOnUiThread(()->{status.setText(message);Toast.makeText(this,"Lock-screen action finished; see status",Toast.LENGTH_LONG).show();h.postDelayed(poll,10000);});},"Apply lock photos").start();});
 button(root,"Copy report",()->{String r=status.getText().toString();try{r=currentReport();status.setText(r);}catch(Exception e){r+="\nReport fetch failed: "+e;}((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Wallpaper layer",r));Toast.makeText(this,"Report copied",Toast.LENGTH_SHORT).show();});
 ScrollView scroll=new ScrollView(this);scroll.addView(root);setContentView(scroll);Shizuku.addRequestPermissionResultListener(permission);
 if(getIntent().getBooleanExtra("auto_enable",false)){
  getIntent().removeExtra("auto_enable");
  h.post(()->{try{
   if(!photo.exists()||!Shizuku.pingBinder()||Shizuku.checkSelfPermission()!=0){status.setText("Choose a photo and authorize Shizuku, then enable wallpaper.");return;}
   startOnConnect=true;connecting=true;args=new Shizuku.UserServiceArgs(new ComponentName(this,HostLauncher.class)).daemon(true).processNameSuffix("wallpaper_layer").version(16);Shizuku.bindUserService(args,connection);
  }catch(Exception e){connecting=false;status.setText("Could not start custom wallpaper: "+e);}});
 }

 }
 void button(LinearLayout l,String label,Runnable action){Button b=new Button(this);b.setText(label);b.setOnClickListener(v->action.run());l.addView(b);}
 void startRemote(){startOnConnect=false;new File(getFilesDir(),"stop-layer").delete();try(ParcelFileDescriptor fd=ParcelFileDescriptor.open(photo,ParcelFileDescriptor.MODE_READ_ONLY)){status.setText(call(1,fd));h.removeCallbacks(poll);h.postDelayed(poll,500);}catch(Exception e){status.setText(e.toString());}}
 String call(int code,ParcelFileDescriptor fd)throws Exception{if(remote==null)throw new IllegalStateException("Not connected");Parcel p=Parcel.obtain(),r=Parcel.obtain();try{p.writeInterfaceToken(HostLauncher.TOKEN);if(code==1)p.writeTypedObject(fd,0);remote.transact(code,p,r,0);r.readException();return r.readString();}finally{p.recycle();r.recycle();}}
 final Runnable poll=new Runnable(){public void run(){try{status.setText(currentReport());}catch(Exception e){status.setText(readSavedReport()+"\nLauncher: "+e);}h.postDelayed(this,1000);}};
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==2&&result==RESULT_OK&&data!=null){status.setText("Loading photo…");new Thread(()->{try{Bitmap b=ImageDecoder.decodeBitmap(ImageDecoder.createSource(getContentResolver(),data.getData()),(d,i,s)->{d.setAllocator(ImageDecoder.ALLOCATOR_SOFTWARE);int m=Math.max(i.getSize().getWidth(),i.getSize().getHeight());if(m>1600)d.setTargetSampleSize((m+1599)/1600);});File tmp=new File(getFilesDir(),"photo-next.jpg");try(FileOutputStream out=new FileOutputStream(tmp)){if(!b.compress(Bitmap.CompressFormat.JPEG,90,out))throw new IOException("Photo encoding failed");}java.nio.file.Files.move(tmp.toPath(),photo.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING,java.nio.file.StandardCopyOption.ATOMIC_MOVE);b.recycle();runOnUiThread(()->status.setText("Photo saved. If enabled, it updates automatically; otherwise tap Enable custom wallpaper."));}catch(Exception e){runOnUiThread(()->status.setText("Photo failed: "+e));}}).start();}}
 protected void onResume(){super.onResume();h.removeCallbacks(poll);h.post(poll);h.postDelayed(()->reconnectForReport(),500);}
 void reconnectForReport(){try{if(remote!=null||connecting||!new File(getFilesDir(),"layer-report.txt").exists()||!Shizuku.pingBinder()||Shizuku.checkSelfPermission()!=0)return;connecting=true;startOnConnect=false;args=new Shizuku.UserServiceArgs(new ComponentName(this,HostLauncher.class)).daemon(true).processNameSuffix("wallpaper_layer").version(16);Shizuku.bindUserService(args,connection);}catch(Exception e){connecting=false;}}
 String currentReport(){String lock="";try{lock=new String(java.nio.file.Files.readAllBytes(new File(getFilesDir(),"lock-photo-status.txt").toPath()),java.nio.charset.StandardCharsets.UTF_8);}catch(Exception ignored){}return "Duo Fold Live "+org.duofold.live.BuildConfig.VERSION_NAME+"\nKeep-awake saved choice: "+getSharedPreferences("standalone",0).getBoolean("auto_keep_cover_awake",true)+"\n"+org.duofold.live.FoldAwakeDefault.status+"\n"+lock+"\n\n"+readSavedReport()+"\nObserver connection: "+(remote!=null&&remote.isBinderAlive()?"connected":"disconnected; host trace is saved independently");}
 String readSavedReport(){try{
  File f=new File(getFilesDir(),"layer-report.txt");String report=new String(java.nio.file.Files.readAllBytes(f.toPath()),java.nio.charset.StandardCharsets.UTF_8);
  long age=Math.max(0,System.currentTimeMillis()-f.lastModified());
  return "Duo Wallpaper Layer 0.13 diagnostics\nReport source: wallpaper host file\nRead elapsed ms: "+SystemClock.elapsedRealtime()+"\nSaved report age: "+age+" ms"+(age>15000?" — STALE; host activity unconfirmed":"")+"\n\n"+report;
 }catch(Exception e){return "No saved host report available: "+e+"\nEnable custom wallpaper to start a fresh session.";}}
 protected void onPause(){super.onPause();h.removeCallbacks(poll);}
 protected void onDestroy(){h.removeCallbacksAndMessages(null);Shizuku.removeRequestPermissionResultListener(permission);super.onDestroy();}
}
